# Generated by Django 5.1.1 on 2024-10-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('Productname', models.CharField(blank=True, max_length=100, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('MRP', models.IntegerField(blank=True, null=True)),
                ('Description', models.CharField(blank=True, max_length=300, null=True)),
                ('Countryorigin', models.CharField(blank=True, max_length=100, null=True)),
                ('Manufacturedby', models.CharField(blank=True, max_length=100, null=True)),
                ('Productimage', models.ImageField(blank=True, null=True, upload_to='Product')),
                ('Productimage1', models.ImageField(blank=True, null=True, upload_to='Product')),
                ('Productimage2', models.ImageField(blank=True, null=True, upload_to='Product')),
            ],
        ),
    ]
