# Generated by Django 5.1.1 on 2024-11-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_cartdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='Total',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
