# Generated by Django 5.1.1 on 2024-11-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_checkoutdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='Total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
