# Generated by Django 5.1.1 on 2024-11-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_cartdb_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdb',
            name='mobilenumber',
            field=models.IntegerField(blank=True, max_length=12, null=True),
        ),
    ]
