# Generated by Django 5.1.1 on 2024-11-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_checkoutdb_mobilenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdb',
            name='mobilenumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
